pipeline {
    agent any 
    stages {
        stage('build') {
            steps {
                echo 'building backend images' 
            }
        }
        stage('push') {
            steps {
                echo 'pushing backend images' 
            }
        }
    }
}